### ISSUE TITLE
Not able to add custom commands to configuration

### ISSUE THREAD

**Issue by CodingPenguin1** [alesya-h/linux_detect_tablet_mode#20]
I have a Dell XPS 13 2-in-1 (9310) running Artix Linux. I have installed `[detect-tablet-mode-git](https://aur.archlinux.org/packages/detect-tablet-mode-git/)`.

Here is my configuration file (`~/.config/watch_tablet.yml`):

```
input_device: /dev/input/by-path/platform-INTC1051:00-event

modes:
  laptop:
    - xinput enable "AT Translated Set 2 keyboard"
    - xinput enable "SynPS/2 Synaptics TouchPad"
  tablet:
    - xinput disable "AT Translated Set 2 keyboard"
    - xinput disable "SynPS/2 Synaptics TouchPad"
    - /usr/bin/onboard show
    - touch /home/stark/TABLET
```

The xinput commands run properly, but the onboard and touch commands do not
